- name: Install sudo
  retries: 10
  register: install_result
  until: install_result is succeeded
  package:
    name: sudo
    state: present
  become: true
  tags:
    - install

- name: Install git
  retries: 10
  register: install_result
  until: install_result is succeeded
  package:
    name: git
    state: present
  become: true
  tags:
    - install

- name: Create docker group
  group:
    name: docker
    state: present
  become: true
  tags: ['install']

- name: Ensure group "docker" exists
  group:
    name: docker
    state: present
  tags: ['install']

- name: "Create andock ({{ andock_user }}) user"
  user:
    name: "{{ andock_user }}"
    group: docker
    shell: /bin/bash
    generate_ssh_key: yes
    groups: "sudo"
    ssh_key_bits: 4096
    password: "{{ pw }}"
  become: true
  tags: ['install']

- name: Allow 'sudo' group to user andock (Disable password check)
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo   ALL=(ALL:ALL) NOPASSWD: ALL'
  become: true
  tags: ['install', 'update']

- name: "Copy andock server"
  template:
    src: "templates/andock-server"
    dest: "/usr/local/bin/andock-server"
    owner: root
    mode: "u=rx,g=rx,o=rx"
  become: true
  tags: ['install', 'update']

- name: Ensures {{ andock_user_home }}/.docksal dir exists
  file:
    path: "{{ andock_user_home }}/.docksal"
    state: directory
    recurse: yes
  tags: ['install']
  become: true
  become_user: "{{ andock_user }}"

- name: "Generate docksal.env"
  template:
    src: "{{ docksal_env_template_path }}"
    dest: "{{ andock_user_home }}/.docksal/docksal.env"
    owner: "{{ andock_user }}"
    mode: "u=rw,g=rw,o=r"
  tags: ['install', 'update']
  become: true
  become_user: "{{ andock_user }}"

- name: "Generate andock authorized_keys file"
  shell: "andock-server generate-authorized-keys"
  tags: ['install']
  become: true

- name: "Install docksal"
  shell: "andock-server install"
  tags: ['install']
  become: true
  become_user: "{{ andock_user }}"

- name: "Update docksal"
  shell: "andock-server update"
  tags: ['update']
  become: true
  become_user: "{{ andock_user }}"

- name: Enable sudo password
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo   ALL=(ALL:ALL) NOPASSWD: /usr/sbin/adduser, /usr/sbin/userdel, /sbin/ip, /sbin/ifconfig, /usr/bin/tee'
  become: true
  tags: ['install', 'update']
  when: sudo_nopasswd == false

- name: Please copy and paste the following SSH key to your git user. andock will use it to checkout your target git repository.
  shell: "cat {{ andock_user_home }}/.ssh/id_rsa.pub"
  register: ssh_key
  tags: ['install']
  become: true
  become_user: "{{ andock_user }}"

- name: Please copy and paste the following SSH key to your git user. andock will use it to checkout your target git repository.
  shell: "cat {{ andock_user_home }}/.ssh/id_rsa.pub"
  register: ssh_key
  tags:
    - install
  become: true
  become_user: "{{ andock_user }}"

- name: "Show key"
  debug: msg="{{ ssh_key.stdout_lines }}"
  tags:
    - install
  become: true
  become_user: "{{ andock_user }}"