  - name: Install sudo
    package:
      name: sudo
      state: latest
    become: true
    tags: ['install']

  - name: Install git
    package:
      name: git
      state: latest
    become: true
    tags: ['install']

  - name: Create docker group
    group:
      name: docker
      state: present
    become: true
    tags: ['install']

  - name: Ensure group "docker" exists
    group:
      name: docker
      state: present
    tags: ['install']

  - name: Create andock user
    user:
      name: andock
      group: docker
      shell: /bin/bash
      generate_ssh_key: yes
      groups: "sudo"
      ssh_key_bits: 4096
      password: "{{ pw }}"
    become: true
    tags: ['install']

  - name: Allow 'sudo' group to user andock
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%sudo'
      line: '%sudo   ALL=(ALL:ALL) ALL'
    become: true
    tags: ['install']

  - name: "Copy andock server"
    template:
      src: "templates/andock-server"
      dest: "/usr/local/bin/andock-server"
      owner: root
      mode: "u=rx,g=rx,o=rx"
    become: true
    tags: ['install', 'update']

  - name: "Prepare authorized keys for andock user."
    shell: "andock-server init_keys"
    tags: ['install']
    become: true


  - name: Ensures {{ andock_user_home }}/.docksal dir exists
    file:
      path: "{{ andock_user_home }}/.docksal"
      state: directory
      recurse: yes
    tags: ['install_docksal']

  - name: "Generate docksal.env"
    template:
      src: "{{ docksal_env_template_path }}"
      dest: "{{ andock_user_home }}/.docksal/docksal.env"
      owner: andock
      mode: "u=rx,g=rx,o=rx"
    tags: ['install_docksal', 'update']

  - name: "Install docksal"
    raw: "andock-server install"
    tags: ['install_docksal']
    become: {{ use_become }}

  - name: "Update docksal"
    raw: "andock-server update"
    tags: ['update']
    become: {{ use_become }}

  - name: Please copy and paste the following SSH key to your git user. andock will use it to checkout your target git repository.
    shell: "cat {{ andock_user_home }}/.ssh/id_rsa.pub"
    register: ssh_key
    tags: ['install_docksal']

  - debug: msg="{{ ssh_key.stdout_lines }}"
    tags: ['install_docksal']