  - name: Install sudo
    package:
      name: sudo
      state: latest
    become: true
    tags: ['install']

  - name: Install git
    package:
      name: git
      state: latest
    become: true
    tags: ['install']

  - name: Create docker group
    group:
      name: docker
      state: present
    become: true
    tags: ['install']

  - name: Create andock user
    user:
      name: andock
      group: docker
      shell: /bin/bash
      generate_ssh_key: yes
      groups: "sudo"
      ssh_key_bits: 4096
      password: "{{ pw }}"
    become: true
    tags: ['install']

  - name: Allow 'sudo' group to user andock
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%sudo'
      line: '%sudo   ALL=(ALL:ALL) ALL'
    become: true
    tags: ['install']

  - name: "Copy andock server"
    template:
      src: "templates/andock-server"
      dest: "/usr/local/bin/andock-server"
      owner: root
      mode: "u=rx,g=rx,o=rx"
    become: true
    tags: ['install', 'update']

  - name: Ensures {{ andock_user_home }}/.docksal dir exists
    file:
      path: "{{ andock_user_home }}/.docksal"
      state: directory
      recurse: yes
    tags: ['install']
    become: true
    become_user: andock

  - name: Ensures /root/home/.docksal dir exists
    file:
      path: "/home/root/.docksal"
      state: directory
      recurse: yes
    tags: ['install']
    become: true

  - name: "Generate root docksal.env"
    template:
      src: "{{ docksal_env_template_path }}"
      dest: "/home/root/.docksal/docksal.env"
      owner: root
      mode: "u=rx,g=rx,o=rx"
    become: true
    tags: ['install', 'update']

  - name: "Generate docksal.env"
    template:
      src: "{{ docksal_env_template_path }}"
      dest: "{{ andock_user_home }}/.docksal/docksal.env"
      owner: andock
      mode: "u=rx,g=rx,o=rx"
    become: true
    tags: ['install', 'update']
    become_user: andock

  - name: "Install docksal"
    shell: "andock-server install"
    tags: ['install']
    become: true

  - name: "Update stacks"
    shell: "fin update --stacks"
    tags: ['install', 'update']
    become_user: andock
    become: true

  - name: "Restart docksal as andock user"
    shell: "fin system reset"
    tags: ['install', 'update']
    become_user: andock
    become: true

  - file:
      path: "{{ andock_user_home }}/.ssh/authorized_keys"
      owner: andock
      group: docker
      mode: "600"
    become: true
    tags: ['install']
    ignore_errors: yes

  - name: Please copy and paste the following SSH key to your git user. andock will use it to checkout your target git repository.
    shell: "cat {{ andock_user_home }}/.ssh/id_rsa.pub"
    register: ssh_key
    become: true
    tags: ['install']

  - debug: msg="{{ ssh_key.stdout_lines }}"
    tags: ['install']