  - name: Install sudo.
    package:
      name: sudo
      state: latest
    become: true
    tags: ['install']

  - name: Install git.
    package:
      name: git
      state: latest
    become: true
    tags: ['install']

  - name: Create docker group.
    group:
      name: docker
      state: present
    become: true
    tags: ['install']

  - name: Create andock user.
    user:
      name: andock
      group: docker
      shell: /bin/bash
      generate_ssh_key: yes
      groups: "sudo"
      ssh_key_bits: 4096
      password: "{{ pw }}"
    become: true
    tags: ['install']

  - name: Allow 'sudo' group to user andock.
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%sudo'
      line: '%sudo   ALL=(ALL:ALL) ALL'
    become: true
    tags: ['install']

  - name: "Install andock server."
    template:
      src: "templates/andock-server"
      dest: "/usr/local/bin/andock-server"
      owner: andock
      mode: "u=rx,g=rx,o=rx"
    become: true
    tags: ['install', 'update']
    become: true

  - name: Please copy and paste the following SSH key to your git user. andock will use it to checkout your target git repository.
    shell: "cat {{ HOME }}/.ssh/id_rsa.pub"
    register: ssh_key
    become: true
    tags: ['install']

  - debug: msg="{{ ssh_key.stdout_lines }}"
    tags: ['install']