  - name: Install packages
    retries: 10
    until: install_result|succeeded
    package:
      name: "{{ item }}"
      state: present
    become: true
    register: install_result
    loop:
      - sudo
      - git
    tags:
      - install

  - name: Create docker group
    group:
      name: docker
      state: present
    become: true
    tags:
      - install

  - name: Ensure group "docker" exists
    group:
      name: docker
      state: present
    tags:
      - install

  - name: "Create andock ({{ andock_user }}) user"
    user:
      name: "{{ andock_user }}"
      group: docker
      shell: /bin/bash
      generate_ssh_key: yes
      groups: "sudo"
      ssh_key_bits: 4096
      password: "{{ pw }}"
    become: true
    tags:
      - install

  - name: Allow 'sudo' group to user andock (Disable password check)
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%sudo'
      line: '%sudo   ALL=(ALL:ALL) NOPASSWD: ALL'
    become: true
    tags:
      -install
      -update

  - name: "Copy andock server"
    template:
      src: "templates/andock-server"
      dest: "/usr/local/bin/andock-server"
      owner: root
      mode: "u=rx,g=rx,o=rx"
    become: true
    tags: ['install', 'update']

  - name: Ensures {{ andock_user_home }}/.docksal dir exists
    file:
      path: "{{ andock_user_home }}/.docksal"
      state: directory
      recurse: yes
    tags: ['install']
    become: true
    become_user: "{{ andock_user }}"

  - name: "Generate docksal.env"
    template:
      src: "{{ docksal_env_template_path }}"
      dest: "{{ andock_user_home }}/.docksal/docksal.env"
      owner: "{{ andock_user }}"
      mode: "u=rw,g=rw,o=r"
    tags:
      - install
      - update
    become: true
    become_user: "{{ andock_user }}"

  - name: "Generate andock authorized_keys file"
    command: "andock-server generate-authorized-keys"
    become: true
    tags:
      - install
      - skip_ansible_lint

  - name: "Install docksal"
    command: "andock-server install"
    tags: ['install']
    become: true
    become_user: "{{ andock_user }}"
    args:
      creates: "/usr/local/bin/fin"

  - name: "Update Docksal"
    command: "andock-server update"
    tags:
      - update
      - skip_ansible_lint
    become: true
    become_user: "{{ andock_user }}"

  - name: Enable sudo password
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%sudo'
      line: "%sudo   ALL=(ALL:ALL) NOPASSWD: {{ no_passwd }}"
    become: true
    tags:
      - install
      - update
    when: not sudo_nopasswd

  - name: "Please copy and paste the following SSH key to your git user"
    debug: "{{ lookup('file', andock_user_home + '/.ssh/id_rsa.pub') }}"
    tags: ['install']
    become: true
    become_user: "{{ andock_user }}"
